#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

SDL2 = C:\\SDL2-2.0.8\\i686-w64-mingw32

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = -IC:\\boost_1_68_0 -IC:\\SDL2-2.0.8\\i686-w64-mingw32\\include -IC:\\glew-2.1.0\\include -IC:\\Projects\\FreeImage\\Dist\\x32 -IC:\\projects\\glm
CFLAGS = -Wall -std=c++11 -fexceptions -DUNICODE -DGLEW_STATIC
RESINC = 
LIBDIR = -LC:\\SDL2-2.0.8\\i686-w64-mingw32\\lib -LC:\\glew-2.1.0\\lib\\Release\\Win32 -LC:\\Projects\\FreeImage\\Dist\\x32
LIB = -lglew32s -lopengl32 -lmingw32 -lSDL2main SDL2.dll -luser32 -lgdi32 -lwinmm -ldxguid -lSDL2 -lSDL2_test -lglu32 -lComdlg32 -lFreeImage -lmsimg32
LDFLAGS = 

EXECUTABLE_FILE_NAME = ClothSimulator.exe

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
DEBUG_OUTPUT_DIR = bin\\Debug
OUT_DEBUG = $(DEBUG_OUTPUT_DIR)\\$(EXECUTABLE_FILE_NAME)

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
RELEASE_OUTPUT_DIR = bin\\Release
OUT_RELEASE = $(RELEASE_OUTPUT_DIR)\\$(EXECUTABLE_FILE_NAME)

OBJ_DEBUG = $(OBJDIR_DEBUG)\\src\\btoolbar.o $(OBJDIR_DEBUG)\\src\\bwindow.o $(OBJDIR_DEBUG)\\src\\clothchangelistener.o $(OBJDIR_DEBUG)\\src\\glwindow.o $(OBJDIR_DEBUG)\\src\\main.o $(OBJDIR_DEBUG)\\src\\segment.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\main.o $(OBJDIR_RELEASE)\\src\\btoolbar.o $(OBJDIR_RELEASE)\\src\\bwindow.o $(OBJDIR_RELEASE)\\src\\clothchangelistener.o $(OBJDIR_RELEASE)\\src\\glwindow.o $(OBJDIR_RELEASE)\\src\\main.o $(OBJDIR_RELEASE)\\src\\segment.o

all: before_build build_debug build_release after_build

clean: clean_debug clean_release

before_build: 

after_build: 

before_debug: 
	cmd /c if not exist $(DEBUG_OUTPUT_DIR) md $(DEBUG_OUTPUT_DIR)
	cmd /c if not exist $(OBJDIR_DEBUG)\\src md $(OBJDIR_DEBUG)\\src

after_debug: 
	XCOPY $(SDL2)\\bin\\SDL2.dll $(DEBUG_OUTPUT_DIR) /D /Y

build_debug: before_debug out_debug after_debug

debug: before_build build_debug after_build

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\src\\btoolbar.o: src\\btoolbar.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\btoolbar.cpp -o $(OBJDIR_DEBUG)\\src\\btoolbar.o

$(OBJDIR_DEBUG)\\src\\bwindow.o: src\\bwindow.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\bwindow.cpp -o $(OBJDIR_DEBUG)\\src\\bwindow.o

$(OBJDIR_DEBUG)\\src\\clothchangelistener.o: src\\clothchangelistener.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\clothchangelistener.cpp -o $(OBJDIR_DEBUG)\\src\\clothchangelistener.o

$(OBJDIR_DEBUG)\\src\\glwindow.o: src\\glwindow.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\glwindow.cpp -o $(OBJDIR_DEBUG)\\src\\glwindow.o

$(OBJDIR_DEBUG)\\src\\main.o: src\\main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\main.cpp -o $(OBJDIR_DEBUG)\\src\\main.o

$(OBJDIR_DEBUG)\\src\\segment.o: src\\segment.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\segment.cpp -o $(OBJDIR_DEBUG)\\src\\segment.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)\\src

before_release: 
	cmd /c if not exist $(RELEASE_OUTPUT_DIR) md $(RELEASE_OUTPUT_DIR)
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)
	cmd /c if not exist $(OBJDIR_RELEASE)\\src md $(OBJDIR_RELEASE)\\src

after_release: 
	XCOPY $(SDL2)\\bin\\SDL2.dll $(RELEASE_OUTPUT_DIR) /D /Y

build_release: before_release out_release after_release

release: before_build build_release after_build

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) -mwindows $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\src\\btoolbar.o: src\\btoolbar.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\btoolbar.cpp -o $(OBJDIR_RELEASE)\\src\\btoolbar.o

$(OBJDIR_RELEASE)\\src\\bwindow.o: src\\bwindow.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\bwindow.cpp -o $(OBJDIR_RELEASE)\\src\\bwindow.o

$(OBJDIR_RELEASE)\\src\\clothchangelistener.o: src\\clothchangelistener.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\clothchangelistener.cpp -o $(OBJDIR_RELEASE)\\src\\clothchangelistener.o

$(OBJDIR_RELEASE)\\src\\glwindow.o: src\\glwindow.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\glwindow.cpp -o $(OBJDIR_RELEASE)\\src\\glwindow.o

$(OBJDIR_RELEASE)\\src\\main.o: src\\main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\main.cpp -o $(OBJDIR_RELEASE)\\src\\main.o

$(OBJDIR_RELEASE)\\src\\segment.o: src\\segment.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\segment.cpp -o $(OBJDIR_RELEASE)\\src\\segment.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)
	cmd /c rd $(OBJDIR_RELEASE)\\src

.PHONY: before_build after_build before_debug after_debug clean_debug before_release after_release clean_release

